import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

export function middleware(request: NextRequest) {
  // Intercept POST requests to the root path and return 204 No Content
  // This helps resolve 405 Method Not Allowed errors generated by bots in Vercel logs
  if (request.nextUrl.pathname === '/' && request.method === 'POST') {
    return new NextResponse(null, { status: 204 });
  }

  return NextResponse.next();
}

export const config = {
  matcher: '/',
};
